export const FETCH_HUBS_SITES_REQUEST = "FETCH_HUBS_SITES_REQUEST";
export const FETCH_HUBS_SITES_SUCCESS = "FETCH_HUBS_SITES_SUCCESS";
export const FETCH_HUBS_SITES_ERROR = "FETCH_HUBS_SITES_ERROR";
export const UPDATE_SELECTED_SITE = "UPDATE_SELECTED_SITE";
