export const FETCH_STORE_LOCATIONS_REQUEST = 'FETCH_STORE_LOCATIONS_REQUEST'
export const FETCH_STORE_LOCATIONS_ERROR = 'FETCH_STORE_LOCATIONS_ERROR'
export const FETCH_STORE_LOCATIONS_SUCCESS = 'FETCH_STORE_LOCATIONS_SUCCESS'